{% set name = "csview" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wfxr/csview/archive/v{{ version }}.tar.gz
  sha256: de84f181a6b89101ed150a378eff9583d8f8cbcc4025d06adc4bc3c48085df95

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - csview --help

about:
  home: https://github.com/wfxr/csview
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: High performance csv viewer for cli
  dev_url: https://github.com/wfxr/csview

extra:
  recipe-maintainers:
    - danielnachun
