context:
  version: 1.3.3

package:
  name: csview
  version: ${{ version }}

source:
  url: https://github.com/wfxr/csview/archive/v${{ version }}.tar.gz
  sha256: de84f181a6b89101ed150a378eff9583d8f8cbcc4025d06adc4bc3c48085df95

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - csview --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: High performance csv viewer for cli
  homepage: https://github.com/wfxr/csview
  repository: https://github.com/wfxr/csview

extra:
  recipe-maintainers:
    - danielnachun
