context:
  version: "1.3.4"

package:
  name: csview
  version: ${{ version }}

source:
  url: https://github.com/wfxr/csview/archive/v${{ version }}.tar.gz
  sha256: 91fadcddef511265f4bf39897ce4a65c457ac89ffd8dd742dc209d30bf04d6aa

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - csview --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: High performance csv viewer for cli
  homepage: https://github.com/wfxr/csview
  repository: https://github.com/wfxr/csview

extra:
  recipe-maintainers:
    - danielnachun
